### PR TITLE
Changes in Invoke-MandiantAuditAzureADDomain function

### PR DESCRIPTION
**Pull request by y5158**
I have run this script and found that it was not reporting the SigningCertificate and NextSigningCertificate. 
"Get-MsolDomain -Authentication federated" this command does not return the certificates.
"$federation_data" variables have the correct certificates.

Please review and approve.

### CODE REVIEW

**Comment by jurajsucik** [comment]
Good finding. @dmb2168, this looks good!

**Comment by jurajsucik** [comment]
@y5158 , there is one more issue in the original code. The comparison operator on line 179 should be '-gt' instead of '>'. Please could you fix that as well?

**Comment by y5158** [comment]
> @y5158 , there is one more issue in the original code. The comparison operator on line 179 should be '-gt' instead of '>'. Please could you fix that as well?

I have updated the operator as you mentioned. Also, changed 315336000 (3649 days) to 31536000 (365 days)

**Review by jurajsucik — APPROVED** [review]

**Comment by dmb2168** [comment]
approved thanks!

**Comment by y5158** [comment]
Thanks, @dmb2168 @jurajsucik

**Pull request merged**
